import os
import json
import random
import google.generativeai as genai
from github import Github

# --- SETUP & CONFIGURATION ---
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
REPO_NAME = os.getenv('REPO_NAME')
PR_NUMBER = int(os.getenv('PR_NUMBER'))

# Use the Free Tier friendly alias
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel('gemini-flash-latest')

# --- THE MEME ENGINE (No API Key Required) ---
def get_panic_gif(issue_count):
    """
    Returns a GIF url proportional to the number of bugs found.
    """
    if issue_count == 0:
        # Tier 0: Celebration / Chill
        urls = [
            "https://media.giphy.com/media/11ISwbgCx7UBCw/giphy.gif", # Minions cheering
            "https://media.giphy.com/media/nXxOjZrbnbRxS/giphy.gif", # Obama thumbs up
            "https://media.giphy.com/media/LZElUsjl1Bu6c/giphy.gif"  # Shaq shimmy
        ]
    elif issue_count < 5:
        # Tier 1: Mild Panic / Confusion
        urls = [
            "https://media.giphy.com/media/3o7TKr3nzbh5JE052w/giphy.gif", # Key and Peele sweating
            "https://media.giphy.com/media/QMHoU66sBXqqLqYvGO/giphy.gif", # This is fine dog
            "https://media.giphy.com/media/ma7VlDSlty3DO/giphy.gif"        # Math lady
        ]
    else:
        # Tier 2: Absolute Terror / Destruction
        urls = [
            "https://media.giphy.com/media/nrXif9YExO9EI/giphy.gif", # Donald Glover Fire
            "https://media.giphy.com/media/tXL4FHPSnVJ0A/giphy.gif", # Kim K crying
            "https://media.giphy.com/media/oe33xf3B50fsc/giphy.gif"  # Jonah Hill screaming
        ]
    
    return random.choice(urls)

def get_diff(repo, pr_number):
    pr = repo.get_pull(pr_number)
    diff_content = ""
    print(f"Processing PR #{pr_number}...")

    for file in pr.get_files():
        if file.filename.endswith(('.png', '.jpg', '.lock', '.json', '.svg')):
            print(f"Skipping {file.filename}")
            continue
        diff_content += f"\nFile: {file.filename}\n{file.patch}\n"
    
    return pr, diff_content

def analyze_diff(diff):
    prompt = f"""
    You are a Senior Software Engineer doing a code review.
    Analyze the following git diffs.
    
    YOUR RULES:
    1. Focus on SUBSTANTIAL issues: Bugs, Security, Performance.
    2. IGNORE trivial issues: Formatting, missing comments.
    3. If the code looks good, return an empty list.
    
    OUTPUT FORMAT:
    Respond strictly in JSON format as a list of objects:
    [
        {{"file": "filename.py", "line": 10, "comment": "Issue description"}}
    ]

    Here is the diff:
    {diff}
    """
    response = model.generate_content(prompt)
    clean_response = response.text.replace("```json", "").replace("```", "").strip()
    return clean_response

def post_comment(pr, analysis_json):
    try:
        comments = json.loads(analysis_json)
        issue_count = len(comments)
        
        # 1. Get the Image
        gif_url = get_panic_gif(issue_count)
        
        # 2. Build the Header
        comment_body = f"## 🤖 AI Code Reviewer Report\n"
        comment_body += f"![Reaction]({gif_url})\n\n" # Inject Image Here
        
        # 3. Build the Body
        if issue_count == 0:
            comment_body += "✅ **LGTM!** No critical issues found."
        else:
            comment_body += f"### 🚨 I found {issue_count} issues:\n\n"
            for item in comments:
                comment_body += f"- **{item['file']}** (Line {item.get('line', '?')}): {item['comment']}\n"
            
            comment_body += "\n---\n*Generated by Gemini 1.5 Flash*"

        pr.create_issue_comment(comment_body)
        print("Comment posted successfully.")

    except json.JSONDecodeError:
        print("Failed to parse AI response.")
        pr.create_issue_comment(f"## 🤖 AI Review (Raw Output)\n\n{analysis_json}")

if __name__ == "__main__":
    g = Github(GITHUB_TOKEN)
    repo = g.get_repo(REPO_NAME)
    pr, diff_data = get_diff(repo, PR_NUMBER)

    if not diff_data:
        print("No code changes detected.")
    else:
        print("Analyzing with Gemini...")
        analysis = analyze_diff(diff_data)
        post_comment(pr, analysis)